{
 "title": "La  Palma",
 "time": { "from": "now-7d", "to": "now" },
 "refresh": "2h",
 "templating": {
  "list": [
   { "name": "depth", "label": "depth", "query": "0,10,20,35" }
  ]
 },
 "panels": [
  {
   "title": "Quakes#",
   "type": "stat",
   "description": "Number of Quakes",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  count(event) as count\nFROM quakes\nWHERE\n  $__timeFilter(tstamp)\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Deep Quakes#",
   "type": "stat",
   "description": "Quakes below 20km",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  count(event) as count\nFROM\n  quakes\nWHERE\n  ST_Z(ST_AsText(coors))<=-20 \n  AND\n  $__timeFilter(tstamp)\n"
    }
   ]
  },
  {
   "title": "Middle Quakes#",
   "type": "stat",
   "description": "Quakes between 20 and 10km",
   "gridPos": { "h": 6, "w": 3, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  count(event) as count\nFROM\n  quakes\nWHERE\n  ST_Z(ST_AsText(coors))>-20  AND ST_Z(ST_AsText(coors))<=-10\n  AND\n  $__timeFilter(tstamp)\n"
    }
   ]
  },
  {
   "title": "Shallow Quakes#",
   "type": "stat",
   "description": "Qaukes shallower than 10 km",
   "gridPos": { "h": 6, "w": 3, "x": 9, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  count(event) as count\nFROM\n  quakes\nWHERE\n  ST_Z(ST_AsText(coors))>-10 \n  AND\n  $__timeFilter(tstamp)\n"
    }
   ]
  },
  {
   "title": "Strong Quakes#",
   "type": "stat",
   "description": "Quakes above magnitude 4.5",
   "gridPos": { "h": 6, "w": 3, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  count(event) as count\nFROM\n  quakes\nWHERE\n  ST_M(ST_AsText(coors))>=4.5\n  AND\n  $__timeFilter(tstamp)\n"
    }
   ]
  },
  {
   "title": "Average Quakes#",
   "type": "stat",
   "description": "Quakes between 2.5 and 4.5",
   "gridPos": { "h": 6, "w": 3, "x": 15, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  count(event) as count\nFROM\n  quakes\nWHERE\n  ST_M(ST_AsText(coors))<4.5 AND ST_M(ST_AsText(coors))>=2.5\n  AND\n  $__timeFilter(tstamp)\n"
    }
   ]
  },
  {
   "title": "Weak Quakes#",
   "type": "stat",
   "description": "Quakes weaker than 2.5 magnitude",
   "gridPos": { "h": 6, "w": 3, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  count(event) as count\nFROM\n  quakes\nWHERE\n  ST_M(ST_AsText(coors))<2.5\n  AND\n  $__timeFilter(tstamp)\n"
    }
   ]
  },
  {
   "title": "Quakes Felt#",
   "type": "stat",
   "description": "Quakes that were felt by populations, special machines",
   "gridPos": { "h": 6, "w": 3, "x": 21, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  count(event) as count\nFROM\n  quakes\nWHERE\n  intensity!='NULL'\n  AND\n  $__timeFilter(tstamp)\n"
    }
   ]
  },
  {
   "title": "Quakes per hour",
   "type": "stat",
   "description": "Average number of quake during time period",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \n  avg(cnt)::integer AS avg FROM\n(SELECT\n date_trunc('hour',tstamp) as hour,count(event) as cnt \nFROM quakes\nWHERE\n  $__timeFilter(tstamp)\nGROUP BY hour) a\n\n"
    }
   ]
  },
  {
   "title": "Quakes per hour",
   "type": "stat",
   "description": "Median of quakes during time period",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \n  PERCENTILE_CONT(0.5) WITHIN GROUP(ORDER BY cnt) as median FROM\n(SELECT\n date_trunc('hour',tstamp) as hour,count(event) as cnt \nFROM quakes\nWHERE\n  $__timeFilter(tstamp)\nGROUP BY hour) a\n"
    }
   ]
  },
  {
   "title": "Quakes felt per hour",
   "type": "stat",
   "description": "Median of quakes during time period",
   "gridPos": { "h": 6, "w": 3, "x": 6, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \n  PERCENTILE_CONT(0.5) WITHIN GROUP(ORDER BY cnt) as median FROM\n(SELECT\n date_trunc('hour',tstamp) as hour,count(a.event) as cnt \nFROM quakes a INNER JOIN intensities b ON a.event=b.event\nWHERE\n  $__timeFilter(tstamp)\nGROUP BY hour) a\n"
    }
   ]
  },
  {
   "title": "Shallow depth median",
   "type": "stat",
   "description": "Median of quake depth during time period",
   "gridPos": { "h": 6, "w": 3, "x": 9, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "lengthkm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \n  PERCENTILE_CONT(0.5) WITHIN GROUP(ORDER BY deep) as median FROM\n(SELECT\n date_trunc('hour',tstamp) as hour,ST_Z(ST_AsText(coors)) as deep \nFROM quakes \nWHERE\n  $__timeFilter(tstamp)\n  AND ST_Z(ST_AsText(coors))>-20\n) a\n"
    }
   ]
  },
  {
   "title": "Deep depth median",
   "type": "stat",
   "description": "Median of quake depth during time period",
   "gridPos": { "h": 6, "w": 3, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "lengthkm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \n  PERCENTILE_CONT(0.5) WITHIN GROUP(ORDER BY deep) as median FROM\n(SELECT\n date_trunc('hour',tstamp) as hour,ST_Z(ST_AsText(coors)) as deep \nFROM quakes \nWHERE\n  $__timeFilter(tstamp)\n  AND ST_Z(ST_AsText(coors))<=-20\n) a\n"
    }
   ]
  },
  {
   "title": "Shallow Quakes magnitude",
   "type": "gauge",
   "description": "Median of quake depth during time period",
   "gridPos": { "h": 6, "w": 3, "x": 15, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \n  PERCENTILE_CONT(0.5) WITHIN GROUP(ORDER BY magnitude) as median FROM\n(SELECT\n date_trunc('hour',tstamp) as hour,ST_M(ST_AsText(coors)) as magnitude\nFROM quakes \nWHERE\n  $__timeFilter(tstamp)\n  AND ST_Z(ST_AsText(coors))>-20\n) a\n"
    }
   ]
  },
  {
   "title": "Deep Quakes magnitude",
   "type": "gauge",
   "description": "Median of quake depth during time period",
   "gridPos": { "h": 6, "w": 3, "x": 18, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \n  PERCENTILE_CONT(0.5) WITHIN GROUP(ORDER BY magnitude) as median FROM\n(SELECT\n date_trunc('hour',tstamp) as hour,ST_M(ST_AsText(coors)) as magnitude\nFROM quakes \nWHERE\n  $__timeFilter(tstamp)\n  AND ST_Z(ST_AsText(coors))<=-20\n) a\n"
    }
   ]
  },
  {
   "title": "Magnitude distribution (shallow vs deep)",
   "type": "histogram",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(tstamp,$__interval),\n  avg(ST_M(ST_AsText(coors))) AS \"type\"\nFROM quakes\nWHERE\n  $__timeFilter(tstamp) AND\n  ST_Z(ST_AsText(coors)) > -20\nGROUP BY 1\nORDER BY 1"
    },
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(tstamp,$__interval),\n  avg(ST_M(ST_AsText(coors))) AS \"type\"\nFROM quakes\nWHERE\n  $__timeFilter(tstamp) AND\n  ST_Z(ST_AsText(coors)) <= -20\nGROUP BY 1\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Depth distribution",
   "type": "histogram",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(tstamp,$__interval),\n  avg(ST_Z(ST_AsText(coors))) AS \"type\"\nFROM quakes\nWHERE\n  $__timeFilter(tstamp)\nGROUP BY 1\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Events",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 20 },
   "targets": [
    {
     "rawSql": "SELECT\n date_trunc('hour',tstamp) as time,count(event) as cnt \nFROM quakes\nWHERE\n  $__timeFilter(tstamp)\nGROUP BY 1\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Depths",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "lengthkm" } },
   "targets": [
    {
     "rawSql": "SELECT\n date_trunc('hour',tstamp) as time,min(ST_Z(ST_AsText(coors))) as min,max(ST_Z(ST_AsText(coors))) as max \nFROM quakes\nWHERE\n  $__timeFilter(tstamp)\nGROUP BY 1\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Depths Daily Median",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "lengthkm" } },
   "targets": [
    {
     "rawSql": "SELECT \n  date_trunc('day',tstamp) as time,PERCENTILE_CONT(0.5) WITHIN GROUP(ORDER BY ST_Z(ST_AsText(coors))) as median\nFROM quakes\nWHERE\n  ST_Z(ST_AsText(coors))<-1*$depth AND\n  $__timeFilter(tstamp)\nGROUP BY time"
    }
   ]
  },
  {
   "title": "Magnitudes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 44 },
   "targets": [
    {
     "rawSql": "SELECT\n date_trunc('hour',tstamp) as time,min(ST_M(ST_AsText(coors))) as min,max(ST_M(ST_AsText(coors))) as max\nFROM quakes\nWHERE\n  $__timeFilter(tstamp)\nGROUP BY 1\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Magnitudes Daily Median",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 52 },
   "targets": [
    {
     "rawSql": "SELECT \n  date_trunc('day',tstamp) as time,PERCENTILE_CONT(0.5) WITHIN GROUP(ORDER BY ST_M(ST_AsText(coors))) as median\nFROM quakes\nWHERE\n  ST_Z(ST_AsText(coors))<-1*$depth AND\n  $__timeFilter(tstamp)\nGROUP BY time"
    }
   ]
  },
  {
   "title": "Intensities",
   "type": "timeseries",
   "description": "How the quakes were felt",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 60 },
   "targets": [
    {
     "rawSql": "SELECT\n date_trunc('hour',tstamp) as time,min(b.min) as min,max(b.max) as max\nFROM quakes a\nINNER JOIN intensities b ON a.event=b.event\nWHERE\n  $__timeFilter(tstamp)\nGROUP BY 1\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Intensities Daily Median",
   "type": "timeseries",
   "description": "How the quakes were felt",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 68 },
   "targets": [
    {
     "rawSql": "SELECT \n  date_trunc('day',tstamp) as time,PERCENTILE_CONT(0.5) WITHIN GROUP(ORDER BY max) as median\nFROM quakes a\nINNER JOIN intensities b ON a.event=b.event\nWHERE\n  ST_Z(ST_AsText(coors))<-1*$depth AND\n  $__timeFilter(tstamp)\nGROUP BY time\n"
    }
   ]
  },
  {
   "title": "Map Quakes",
   "type": "geomap",
   "gridPos": { "h": 22, "w": 24, "x": 0, "y": 76 },
   "targets": [
    {
     "rawSql": "SELECT\n  tstamp as \"time\",\n  avg(ST_Y(ST_AsText(coors))) AS \"latitude\",\n  avg(ST_X(ST_AsText(coors))) AS \"longitude\"\nFROM quakes\nWHERE\n  ST_Z(ST_AsText(coors))<-1*$depth AND\n  $__timeFilter(tstamp)\nGROUP BY 1\nORDER BY 1\n"
    }
   ]
  },
  {
   "title": "Map Accelerations",
   "type": "geomap",
   "gridPos": { "h": 22, "w": 24, "x": 0, "y": 98 },
   "targets": [
    {
     "rawSql": "SELECT\n  tstamp as \"time\",\n  avg(ST_Y(ST_AsText(coors))) AS \"latitude\",\n  avg(ST_X(ST_AsText(coors))) AS \"longitude\"\nFROM acceleration\nWHERE\n  $__timeFilter(tstamp)\nGROUP BY 1\nORDER BY 1\n"
    }
   ]
  },
  {
   "title": "Seismic Impact",
   "type": "geomap",
   "gridPos": { "h": 22, "w": 24, "x": 0, "y": 120 },
   "targets": [
    {
     "rawSql": "SELECT\n  tstamp as \"time\",\n  ST_Y(ST_AsText(b.coors)) AS \"latitude\",\n  ST_X(ST_AsText(b.coors)) AS \"longitude\",\n  (min+max)/2 as mag\nFROM quakes a\nINNER JOIN intensity_coors b \nON a.event=b.event\nWHERE\n  $__timeFilter(tstamp)\nORDER BY 1\n"
    }
   ]
  }
 ]
}